### ISSUE TITLE
requirement of pygreenx  for unittest   should be added to README.md

### ISSUE THREAD

**Issue by mailhexu** [nomad-coe/greenX#51]
It is not clear from the documentation that pygreenx should be installed for the unit tests.  And the way to install it should be added too, although the source code can be found in the python directory. Indeed without knowing that the unit tests 2 and 3 will fail.

**Comment by aziziph** [comment]
@AlexBuccheri 
Could you please take care of this?

**Comment by AlexBuccheri** [comment]
Could @mailhexu be more specific as to what they'd like to see, and where?

In the top-level README, it states:

```
## Running the Tests

GreenX uses pytest as its regression testing framework, in conjunction with 
some custom python modules. First, one must ensure that the python utilities
are installed. From the GreenX root directory:

```bash
cd python
pip install -e .
```
```

In the time-frequency README.md, it states:

```
## Running the Tests

Application tests are run with the pytest framework. Having installed `pygreenx`
(see the top-level README) change to `<GX_ROOT>/<BUILD_DIR>` and type `ctest`. 
Additionally, one can change to the test folder and explicitly run the pytest 
command from there:

```bash
cd <GX_ROOT>/<BUILD_DIR>/test/time-frequency
pytest -s 
# or
pytest -s test_name.py
```
```

Things I could think to improve this are:

- Explicitly mention the name pygreenx in the top-level details (instead of saying python utilities)
- Have CMake check if pygreenx is installed, and give instructions if not

**Comment by mailhexu** [comment]
Sorry that I didn't notice the first part.  When I was trying the unit test part, I only searched in the Unit Test section. 
But indeed what you proposed for the improvement is nice.

**Comment by AlexBuccheri** [comment]
@mailhexu In that case I'll reopen the issue such that I can create an MR that addresses the points I've suggested
